# Copyright 2021 iLogtail Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: "2"
run:
  concurrency: 4
  modules-download-mode: readonly
  issues-exit-code: 1
  tests: true
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
linters:
  enable:
    - copyloopvar
    - gocritic
    - gosec
    - govet
    - misspell
    - revive
    - staticcheck
    - unconvert
    - unparam
  disable:
    - errcheck
  settings:
    gosec:
      excludes:
        - G115
        - G204
        - G301
        - G306
    govet:
      disable:
        - fieldalignment
      enable-all: true
      settings:
        printf:
          funcs:
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
    misspell:
      locale: US
    revive:
      rules:
        - name: unused-parameter
          disabled: true
    staticcheck:
      checks:
        - all
        - -QF*
        - -ST*
  exclusions:
    generated: lax
    rules:
      - linters:
          - errcheck
          - gosec
        path: .*_test.go
      - linters:
          - revive
        path: plugins/all
      - linters:
          - revive
        path: plugins/test
      - linters:
          - staticcheck
        text: 'SA1019:'
      - linters:
          - gosec
        path: pkg/selfmonitor/alarm_type.go
        text: 'G101:'
    paths:
      - plugins/input/journal/unit.go
      - plugins/input/journal/follow.go
      - plugins/input/prometheus/sls_writer.go
      - plugin_main/plugin_http.go
      - (^|/)core($|/)
      - (^|/)vendor($|/)
      - (^|/)external($|/)
      - (^|/)plugins/input/input_wineventlog($|/)
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/alibaba/ilogtail
  exclusions:
    generated: lax
    paths:
      - plugins/input/journal/unit.go
      - plugins/input/journal/follow.go
      - plugins/input/prometheus/sls_writer.go
      - plugin_main/plugin_http.go
      - (^|/)core($|/)
      - (^|/)vendor($|/)
      - (^|/)external($|/)
      - (^|/)plugins/input/input_wineventlog($|/)
