// Copyright 2023 iLogtail Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package util

type AlarmType int

// 与 core/monitor/AlarmManager.h 中的 AlarmType 同步
const (
	USER_CONFIG_ALARM AlarmType = iota
	GLOBAL_CONFIG_ALARM
	DOMAIN_SOCKET_BIND_ALARM
	SECONDARY_READ_WRITE_ALARM
	LOGFILE_PERMINSSION_ALARM
	SEND_QUOTA_EXCEED_ALARM
	LOGTAIL_CRASH_ALARM
	INOTIFY_DIR_NUM_LIMIT_ALARM
	EPOLL_ERROR_ALARM
	DISCARD_DATA_ALARM
	READ_LOG_DELAY_ALARM
	MULTI_CONFIG_MATCH_ALARM
	REGISTER_INOTIFY_FAIL_ALARM
	LOGTAIL_CONFIG_ALARM
	ENCRYPT_DECRYPT_FAIL_ALARM
	LOG_GROUP_PARSE_FAIL_ALARM
	METRIC_GROUP_PARSE_FAIL_ALARM
	LOGDIR_PERMISSION_ALARM
	REGEX_MATCH_ALARM
	DISCARD_SECONDARY_ALARM
	BINARY_UPDATE_ALARM
	CONFIG_UPDATE_ALARM
	CHECKPOINT_ALARM
	CATEGORY_CONFIG_ALARM
	INOTIFY_EVENT_OVERFLOW_ALARM
	INVALID_MEMORY_ACCESS_ALARM
	ENCODING_CONVERT_ALARM
	SPLIT_LOG_FAIL_ALARM
	OPEN_LOGFILE_FAIL_ALARM
	SEND_DATA_FAIL_ALARM
	PARSE_TIME_FAIL_ALARM
	OUTDATED_LOG_ALARM
	STREAMLOG_TCP_SOCKET_BIND_ALARM
	SKIP_READ_LOG_ALARM
	SEND_COMPRESS_FAIL_ALARM
	PARSE_LOG_FAIL_ALARM
	LOG_TRUNCATE_ALARM
	DIR_EXCEED_LIMIT_ALARM
	STAT_LIMIT_ALARM
	FILE_READER_EXCEED_ALARM
	LOGTAIL_CRASH_STACK_ALARM
	MODIFY_FILE_EXCEED_ALARM
	OPEN_FILE_LIMIT_ALARM
	TOO_MANY_CONFIG_ALARM
	SAME_CONFIG_ALARM
	PROCESS_QUEUE_BUSY_ALARM
	DROP_LOG_ALARM
	CAST_SENSITIVE_WORD_ALARM
	PROCESS_TOO_SLOW_ALARM
	LOAD_LOCAL_EVENT_ALARM
	WINDOWS_WORKER_START_HINTS_ALARM
	HOLD_ON_TOO_SLOW_ALARM
	INNER_PROFILE_ALARM
	FUSE_FILE_TRUNCATE_ALARM
	SENDING_COSTS_TOO_MUCH_TIME_ALARM
	UNEXPECTED_FILE_TYPE_MODE_ALARM
	LOG_GROUP_WAIT_TOO_LONG_ALARM
	CHECKPOINT_V2_ALARM
	EXACTLY_ONCE_ALARM
	READ_STOPPED_CONTAINER_ALARM
	INVALID_CONTAINER_PATH_ALARM
	COMPRESS_FAIL_ALARM
	SERIALIZE_FAIL_ALARM
	RELABEL_METRIC_FAIL_ALARM
	REGISTER_HANDLERS_TOO_SLOW_ALARM
	PLUGIN_INIT_ALARM
	PLUGIN_START_ALARM
	PLUGIN_RUNTIME_ALARM
	PLUGIN_STOP_ALARM
	DOCKER_CENTER_ALARM
	KUBERNETES_META_ALARM
	INTERNAL_SERVICE_ERROR
	ALL_LOGTAIL_ALARM_NUM
)

func (t AlarmType) String() string {
	return [...]string{
		"USER_CONFIG_ALARM",
		"GLOBAL_CONFIG_ALARM",
		"DOMAIN_SOCKET_BIND_ALARM",
		"SECONDARY_READ_WRITE_ALARM",
		"LOGFILE_PERMINSSION_ALARM",
		"SEND_QUOTA_EXCEED_ALARM",
		"LOGTAIL_CRASH_ALARM",
		"INOTIFY_DIR_NUM_LIMIT_ALARM",
		"EPOLL_ERROR_ALARM",
		"DISCARD_DATA_ALARM",
		"READ_LOG_DELAY_ALARM",
		"MULTI_CONFIG_MATCH_ALARM",
		"REGISTER_INOTIFY_FAIL_ALARM",
		"LOGTAIL_CONFIG_ALARM",
		"ENCRYPT_DECRYPT_FAIL_ALARM",
		"LOG_GROUP_PARSE_FAIL_ALARM",
		"METRIC_GROUP_PARSE_FAIL_ALARM",
		"LOGDIR_PERMISSION_ALARM",
		"REGEX_MATCH_ALARM",
		"DISCARD_SECONDARY_ALARM",
		"BINARY_UPDATE_ALARM",
		"CONFIG_UPDATE_ALARM",
		"CHECKPOINT_ALARM",
		"CATEGORY_CONFIG_ALARM",
		"INOTIFY_EVENT_OVERFLOW_ALARM",
		"INVALID_MEMORY_ACCESS_ALARM",
		"ENCODING_CONVERT_ALARM",
		"SPLIT_LOG_FAIL_ALARM",
		"OPEN_LOGFILE_FAIL_ALARM",
		"SEND_DATA_FAIL_ALARM",
		"PARSE_TIME_FAIL_ALARM",
		"OUTDATED_LOG_ALARM",
		"STREAMLOG_TCP_SOCKET_BIND_ALARM",
		"SKIP_READ_LOG_ALARM",
		"SEND_COMPRESS_FAIL_ALARM",
		"PARSE_LOG_FAIL_ALARM",
		"LOG_TRUNCATE_ALARM",
		"DIR_EXCEED_LIMIT_ALARM",
		"STAT_LIMIT_ALARM",
		"FILE_READER_EXCEED_ALARM",
		"LOGTAIL_CRASH_STACK_ALARM",
		"MODIFY_FILE_EXCEED_ALARM",
		"OPEN_FILE_LIMIT_ALARM",
		"TOO_MANY_CONFIG_ALARM",
		"SAME_CONFIG_ALARM",
		"PROCESS_QUEUE_BUSY_ALARM",
		"DROP_LOG_ALARM",
		"CAST_SENSITIVE_WORD_ALARM",
		"PROCESS_TOO_SLOW_ALARM",
		"LOAD_LOCAL_EVENT_ALARM",
		"WINDOWS_WORKER_START_HINTS_ALARM",
		"HOLD_ON_TOO_SLOW_ALARM",
		"INNER_PROFILE_ALARM",
		"FUSE_FILE_TRUNCATE_ALARM",
		"SENDING_COSTS_TOO_MUCH_TIME_ALARM",
		"UNEXPECTED_FILE_TYPE_MODE_ALARM",
		"LOG_GROUP_WAIT_TOO_LONG_ALARM",
		"CHECKPOINT_V2_ALARM",
		"EXACTLY_ONCE_ALARM",
		"READ_STOPPED_CONTAINER_ALARM",
		"INVALID_CONTAINER_PATH_ALARM",
		"COMPRESS_FAIL_ALARM",
		"SERIALIZE_FAIL_ALARM",
		"RELABEL_METRIC_FAIL_ALARM",
		"REGISTER_HANDLERS_TOO_SLOW_ALARM",
		"PLUGIN_INIT_ALARM",
		"PLUGIN_START_ALARM",
		"PLUGIN_RUNTIME_ALARM",
		"PLUGIN_STOP_ALARM",
		"DOCKER_CENTER_ALARM",
		"KUBERNETES_META_ALARM",
		"INTERNAL_SERVICE_ERROR",
		"ALL_LOGTAIL_ALARM_NUM",
	}[t]
}
