FROM sls-opensource-registry.cn-shanghai.cr.aliyuncs.com/loongcollector-community-edition/loongcollector-build-linux:2.1.19

USER root

RUN mkdir -p /tmp/loongcollector

WORKDIR /root
COPY . ./loongcollector

RUN python3 -m ensurepip

WORKDIR /root/loongcollector/test
RUN python3 -m pip install -r requirements.txt

CMD ["sh", "-c", "while true; do sleep 3600; done"]