# Copyright 2021 iLogtail Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# AgentSight (coolbpf / vendored openssl-sys): perl + IPC::Cmd + Data::Dumper + openssl-devel are preinstalled
# in loongcollector-build-linux 2.1.17+; gen_build.sh still verifies required Perl modules.
FROM sls-opensource-registry.cn-shanghai.cr.aliyuncs.com/loongcollector-community-edition/loongcollector-build-linux:2.1.17 AS build

USER root
ENV PERL=/usr/bin/perl
ENV PERL5LIB=/usr/share/perl5:/usr/lib64/perl5/vendor_perl:/usr/share/perl5/vendor_perl:/usr/lib64/perl5
# openssl-sys (agentsight): avoid system LibreSSL/OpenSSL mismatch; vendored build unless overridden.
# To link system OpenSSL instead, set OPENSSL_NO_VENDOR=1 here and use supported libssl-dev.
ENV OPENSSL_NO_VENDOR=0
WORKDIR /src
COPY . .

ARG HOST_OS=Linux
ARG VERSION=3.3.5

RUN --mount=type=ssh sh generated_files/gen_build.sh
