# Copyright 2021 iLogtail Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM ubuntu:25.10 AS build
ARG VERSION=3.3.5
ARG TARGETPLATFORM
WORKDIR /usr/local
# Copy the specific architecture package
COPY dist/loongcollector-${VERSION}.linux-${TARGETPLATFORM##*/}.tar.gz .
RUN tar -xzf loongcollector-${VERSION}.linux-${TARGETPLATFORM##*/}.tar.gz

FROM ubuntu:25.10 AS release

ENV container=docker

ARG HOST_OS=Linux
ARG VERSION=3.3.5
ARG TARGETPLATFORM
ARG TARGETARCH

COPY --from=build /usr/local/loongcollector-${VERSION} /usr/local/loongcollector
RUN chown -R $(whoami) /usr/local/loongcollector/ && \
    chmod 755 /usr/local/loongcollector/loongcollector && \
    mkdir -p /usr/local/loongcollector/data/checkpoint

# Install runtime dependencies (Kerberos/SASL libs for Kafka)
RUN if [ "$HOST_OS" = "Linux" ]; then \
        apt-get update && apt-get install -y \
            libsasl2-2 \
            libsasl2-modules \
            libsasl2-modules-gssapi-mit \
            libkrb5-3 \
            libk5crypto3 \
            libgssapi-krb5-2 && \
        apt-get clean && rm -rf /var/lib/apt/lists/*; \
    fi

# Provide CentOS-compiled SASL libraries for librdkafka (expects libsasl2.so.3)
COPY --from=sls-opensource-registry.cn-shanghai.cr.aliyuncs.com/loongcollector-community-edition/loongcollector-build-linux:2.1.17 /usr/lib64/libsasl2.so.3 /tmp/sasl-compat/libsasl2.so.3
COPY --from=sls-opensource-registry.cn-shanghai.cr.aliyuncs.com/loongcollector-community-edition/loongcollector-build-linux:2.1.17 /usr/lib64/libsasl2.so.3.0.0 /tmp/sasl-compat/libsasl2.so.3.0.0
COPY --from=sls-opensource-registry.cn-shanghai.cr.aliyuncs.com/loongcollector-community-edition/loongcollector-build-linux:2.1.17 /usr/lib64/sasl2 /tmp/sasl-compat/sasl2
RUN set -eux; \
    case "${TARGETARCH}" in \
        amd64) LIB_DIR="/usr/lib/x86_64-linux-gnu" ;; \
        arm64) LIB_DIR="/usr/lib/aarch64-linux-gnu" ;; \
        *) echo "Unsupported TARGETARCH: ${TARGETARCH}" >&2; exit 1 ;; \
    esac; \
    mkdir -p "${LIB_DIR}"; \
    cp /tmp/sasl-compat/libsasl2.so.3 "${LIB_DIR}/libsasl2.so.3"; \
    cp /tmp/sasl-compat/libsasl2.so.3.0.0 "${LIB_DIR}/libsasl2.so.3.0.0"; \
    cp -a /tmp/sasl-compat/sasl2 "${LIB_DIR}/sasl2"; \
    ln -sf "${LIB_DIR}/libsasl2.so.3" /usr/lib/libsasl2.so.3; \
    ln -sf "${LIB_DIR}/libsasl2.so.3.0.0" /usr/lib/libsasl2.so.3.0.0; \
    rm -rf /tmp/sasl-compat

WORKDIR /usr/local/loongcollector
RUN mkdir -p /usr/local/loongcollector/conf/instance_config/local
RUN mkdir -p /usr/local/loongcollector/log
RUN mkdir -p /usr/local/loongcollector/data
RUN mkdir -p /usr/local/loongcollector/run

COPY example_config/start_with_docker/loongcollector_config.json /usr/local/loongcollector/conf/instance_config/local/loongcollector_config.json
COPY scripts/loongcollector_control.sh /usr/local/loongcollector/

ENV HTTP_PROBE_PORT=7953 \
    ALIYUN_LOGTAIL_USER_DEFINED_ID=default \
    docker_file_cache_path=checkpoint/docker_path_config.json \
    LOONGCOLLECTOR_VERSION=$VERSION \
    HOST_OS=$HOST_OS

CMD ["/usr/local/loongcollector/loongcollector_control.sh", "start_and_block"] 