# Copyright 2021 iLogtail Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM sls-opensource-registry.cn-shanghai.cr.aliyuncs.com/loongcollector-community-edition/loongcollector-build-linux:2.1.17

ARG HOST_OS=Linux
ARG VERSION=0.0.1

USER root
ENV container=docker

RUN yum update -y && yum -y install systemd initscripts && yum -y clean all && rm -fr /var/cache

RUN mkdir -p /usr/local/loongcollector/conf/instance_config/local
RUN mkdir -p /usr/local/loongcollector/log
RUN mkdir -p /usr/local/loongcollector/data
RUN mkdir -p /usr/local/loongcollector/run

COPY --from=build /src/core/build/loongcollector /usr/local/loongcollector/
COPY ./scripts/loongcollector_control.sh /usr/local/loongcollector/
COPY ./scripts/download_ebpflib.sh /tmp/

RUN chown -R $(whoami) /usr/local/loongcollector && \
    chmod 755 /usr/local/loongcollector/loongcollector && \
    mkdir -p /usr/local/loongcollector/data/checkpoint && \
    if [ `uname -m` = "x86_64" ]; then /tmp/download_ebpflib.sh /usr/local/loongcollector; fi && \
    rm /tmp/download_ebpflib.sh

COPY --from=build /src/output/libGoPluginBase.so /usr/local/loongcollector/
COPY --from=build /src/example_config/quick_start/loongcollector_config.json /usr/local/loongcollector/conf/instance_config/local/loongcollector_config.json
COPY --from=build /src/core/build/go_pipeline/libGoPluginAdapter.so /usr/local/loongcollector/
COPY --from=build /src/core/build/ebpf/driver/libeBPFDriver.so /usr/local/loongcollector/
COPY --from=build /src/core/build/_thirdparty/coolbpf/src/profiler/release/libprofiler.so /usr/local/loongcollector/

ENV HOST_OS=$HOST_OS \
    LOONGCOLLECTOR_VERSION=$VERSION \
    HTTP_PROBE_PORT=7953 \
    ALIYUN_LOGTAIL_USER_DEFINED_ID=default \
    docker_file_cache_path=checkpoint/docker_path_config.json

EXPOSE 18689

CMD ["/usr/local/loongcollector/loongcollector_control.sh", "start_and_block"]
