// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: metric_event.proto

package protocol

import (
	encoding_binary "encoding/binary"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UntypedValueMetricType int32

const (
	UntypedValueMetricType_METRIC_TYPE_COUNTER UntypedValueMetricType = 0
	UntypedValueMetricType_METRIC_TYPE_GAUGE   UntypedValueMetricType = 1
)

var UntypedValueMetricType_name = map[int32]string{
	0: "METRIC_TYPE_COUNTER",
	1: "METRIC_TYPE_GAUGE",
}

var UntypedValueMetricType_value = map[string]int32{
	"METRIC_TYPE_COUNTER": 0,
	"METRIC_TYPE_GAUGE":   1,
}

func (x UntypedValueMetricType) String() string {
	return proto.EnumName(UntypedValueMetricType_name, int32(x))
}

func (UntypedValueMetricType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7e0c5b3c1d4100c7, []int{0}
}

type UntypedSingleValue struct {
	Value                float64  `protobuf:"fixed64,1,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UntypedSingleValue) Reset()         { *m = UntypedSingleValue{} }
func (m *UntypedSingleValue) String() string { return proto.CompactTextString(m) }
func (*UntypedSingleValue) ProtoMessage()    {}
func (*UntypedSingleValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e0c5b3c1d4100c7, []int{0}
}
func (m *UntypedSingleValue) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UntypedSingleValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UntypedSingleValue.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UntypedSingleValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UntypedSingleValue.Merge(m, src)
}
func (m *UntypedSingleValue) XXX_Size() int {
	return m.Size()
}
func (m *UntypedSingleValue) XXX_DiscardUnknown() {
	xxx_messageInfo_UntypedSingleValue.DiscardUnknown(m)
}

var xxx_messageInfo_UntypedSingleValue proto.InternalMessageInfo

func (m *UntypedSingleValue) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type UntypedMultiDoubleValue struct {
	MetricType           UntypedValueMetricType `protobuf:"varint,1,opt,name=MetricType,proto3,enum=logtail.models.UntypedValueMetricType" json:"MetricType,omitempty"`
	Value                float64                `protobuf:"fixed64,2,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *UntypedMultiDoubleValue) Reset()         { *m = UntypedMultiDoubleValue{} }
func (m *UntypedMultiDoubleValue) String() string { return proto.CompactTextString(m) }
func (*UntypedMultiDoubleValue) ProtoMessage()    {}
func (*UntypedMultiDoubleValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e0c5b3c1d4100c7, []int{1}
}
func (m *UntypedMultiDoubleValue) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UntypedMultiDoubleValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UntypedMultiDoubleValue.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UntypedMultiDoubleValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UntypedMultiDoubleValue.Merge(m, src)
}
func (m *UntypedMultiDoubleValue) XXX_Size() int {
	return m.Size()
}
func (m *UntypedMultiDoubleValue) XXX_DiscardUnknown() {
	xxx_messageInfo_UntypedMultiDoubleValue.DiscardUnknown(m)
}

var xxx_messageInfo_UntypedMultiDoubleValue proto.InternalMessageInfo

func (m *UntypedMultiDoubleValue) GetMetricType() UntypedValueMetricType {
	if m != nil {
		return m.MetricType
	}
	return UntypedValueMetricType_METRIC_TYPE_COUNTER
}

func (m *UntypedMultiDoubleValue) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type UntypedMultiDoubleValues struct {
	Values               map[string]*UntypedMultiDoubleValue `protobuf:"bytes,1,rep,name=Values,proto3" json:"Values,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *UntypedMultiDoubleValues) Reset()         { *m = UntypedMultiDoubleValues{} }
func (m *UntypedMultiDoubleValues) String() string { return proto.CompactTextString(m) }
func (*UntypedMultiDoubleValues) ProtoMessage()    {}
func (*UntypedMultiDoubleValues) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e0c5b3c1d4100c7, []int{2}
}
func (m *UntypedMultiDoubleValues) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UntypedMultiDoubleValues) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UntypedMultiDoubleValues.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UntypedMultiDoubleValues) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UntypedMultiDoubleValues.Merge(m, src)
}
func (m *UntypedMultiDoubleValues) XXX_Size() int {
	return m.Size()
}
func (m *UntypedMultiDoubleValues) XXX_DiscardUnknown() {
	xxx_messageInfo_UntypedMultiDoubleValues.DiscardUnknown(m)
}

var xxx_messageInfo_UntypedMultiDoubleValues proto.InternalMessageInfo

func (m *UntypedMultiDoubleValues) GetValues() map[string]*UntypedMultiDoubleValue {
	if m != nil {
		return m.Values
	}
	return nil
}

type MetricEvent struct {
	Timestamp uint64            `protobuf:"varint,1,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Name      []byte            `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Tags      map[string][]byte `protobuf:"bytes,3,rep,name=Tags,proto3" json:"Tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Types that are valid to be assigned to Value:
	//
	//	*MetricEvent_UntypedSingleValue
	//	*MetricEvent_UntypedMultiDoubleValues
	Value                isMetricEvent_Value `protobuf_oneof:"Value"`
	Metadata             map[string][]byte   `protobuf:"bytes,5,rep,name=Metadata,proto3" json:"Metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *MetricEvent) Reset()         { *m = MetricEvent{} }
func (m *MetricEvent) String() string { return proto.CompactTextString(m) }
func (*MetricEvent) ProtoMessage()    {}
func (*MetricEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e0c5b3c1d4100c7, []int{3}
}
func (m *MetricEvent) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MetricEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MetricEvent.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MetricEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetricEvent.Merge(m, src)
}
func (m *MetricEvent) XXX_Size() int {
	return m.Size()
}
func (m *MetricEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_MetricEvent.DiscardUnknown(m)
}

var xxx_messageInfo_MetricEvent proto.InternalMessageInfo

type isMetricEvent_Value interface {
	isMetricEvent_Value()
	MarshalTo([]byte) (int, error)
	Size() int
}

type MetricEvent_UntypedSingleValue struct {
	UntypedSingleValue *UntypedSingleValue `protobuf:"bytes,4,opt,name=UntypedSingleValue,proto3,oneof" json:"UntypedSingleValue,omitempty"`
}
type MetricEvent_UntypedMultiDoubleValues struct {
	UntypedMultiDoubleValues *UntypedMultiDoubleValues `protobuf:"bytes,6,opt,name=UntypedMultiDoubleValues,proto3,oneof" json:"UntypedMultiDoubleValues,omitempty"`
}

func (*MetricEvent_UntypedSingleValue) isMetricEvent_Value()       {}
func (*MetricEvent_UntypedMultiDoubleValues) isMetricEvent_Value() {}

func (m *MetricEvent) GetValue() isMetricEvent_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *MetricEvent) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *MetricEvent) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *MetricEvent) GetTags() map[string][]byte {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *MetricEvent) GetUntypedSingleValue() *UntypedSingleValue {
	if x, ok := m.GetValue().(*MetricEvent_UntypedSingleValue); ok {
		return x.UntypedSingleValue
	}
	return nil
}

func (m *MetricEvent) GetUntypedMultiDoubleValues() *UntypedMultiDoubleValues {
	if x, ok := m.GetValue().(*MetricEvent_UntypedMultiDoubleValues); ok {
		return x.UntypedMultiDoubleValues
	}
	return nil
}

func (m *MetricEvent) GetMetadata() map[string][]byte {
	if m != nil {
		return m.Metadata
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*MetricEvent) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*MetricEvent_UntypedSingleValue)(nil),
		(*MetricEvent_UntypedMultiDoubleValues)(nil),
	}
}

func init() {
	proto.RegisterEnum("logtail.models.UntypedValueMetricType", UntypedValueMetricType_name, UntypedValueMetricType_value)
	proto.RegisterType((*UntypedSingleValue)(nil), "logtail.models.UntypedSingleValue")
	proto.RegisterType((*UntypedMultiDoubleValue)(nil), "logtail.models.UntypedMultiDoubleValue")
	proto.RegisterType((*UntypedMultiDoubleValues)(nil), "logtail.models.UntypedMultiDoubleValues")
	proto.RegisterMapType((map[string]*UntypedMultiDoubleValue)(nil), "logtail.models.UntypedMultiDoubleValues.ValuesEntry")
	proto.RegisterType((*MetricEvent)(nil), "logtail.models.MetricEvent")
	proto.RegisterMapType((map[string][]byte)(nil), "logtail.models.MetricEvent.MetadataEntry")
	proto.RegisterMapType((map[string][]byte)(nil), "logtail.models.MetricEvent.TagsEntry")
}

func init() { proto.RegisterFile("metric_event.proto", fileDescriptor_7e0c5b3c1d4100c7) }

var fileDescriptor_7e0c5b3c1d4100c7 = []byte{
	// 453 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xdf, 0x6e, 0xd3, 0x30,
	0x14, 0xc6, 0xe3, 0x25, 0x2d, 0xeb, 0xc9, 0x98, 0x8a, 0x19, 0x2c, 0x8a, 0x50, 0x34, 0x45, 0x02,
	0xca, 0x2e, 0x72, 0x51, 0x90, 0xf8, 0x27, 0x2e, 0xd8, 0x08, 0x2b, 0x12, 0x19, 0xc8, 0xa4, 0x48,
	0x70, 0x53, 0xb9, 0xab, 0xa9, 0x22, 0xf2, 0x4f, 0x8d, 0x3b, 0x94, 0x37, 0xe1, 0x91, 0xb8, 0xe0,
	0x82, 0x47, 0x40, 0xe5, 0x3d, 0x10, 0xaa, 0x9d, 0xb5, 0x1e, 0x24, 0x68, 0xbb, 0xea, 0xa9, 0x73,
	0x7e, 0xe7, 0xf3, 0xe7, 0xcf, 0x06, 0x9c, 0x30, 0x3e, 0x8b, 0x4e, 0x46, 0xec, 0x94, 0xa5, 0xdc,
	0xcb, 0x67, 0x19, 0xcf, 0xf0, 0x76, 0x9c, 0x4d, 0x39, 0x8d, 0x62, 0x2f, 0xc9, 0x26, 0x2c, 0x2e,
	0xdc, 0x7d, 0xc0, 0xc3, 0x94, 0x97, 0x39, 0x9b, 0xbc, 0x8b, 0xd2, 0x69, 0xcc, 0xde, 0xd3, 0x78,
	0xce, 0xf0, 0x0e, 0xb4, 0x44, 0x61, 0xa1, 0x3d, 0xd4, 0x43, 0x44, 0xfe, 0x71, 0xbf, 0xc0, 0x6e,
	0xd5, 0x1b, 0xcc, 0x63, 0x1e, 0xbd, 0xc8, 0xe6, 0xe3, 0x33, 0xe0, 0x25, 0x40, 0x20, 0xc4, 0xc2,
	0x32, 0x97, 0xd4, 0x76, 0xff, 0x8e, 0x77, 0x5e, 0xcb, 0xab, 0x60, 0x41, 0xac, 0xbb, 0x89, 0x42,
	0xae, 0x85, 0x37, 0x54, 0xe1, 0xef, 0x08, 0xac, 0x06, 0xe5, 0x02, 0xbf, 0x86, 0xb6, 0xac, 0x2c,
	0xb4, 0xa7, 0xf7, 0xcc, 0xfe, 0x83, 0x06, 0xd9, 0x7f, 0x48, 0x4f, 0xfe, 0xf8, 0x29, 0x9f, 0x95,
	0xa4, 0x9a, 0x61, 0x8f, 0xc1, 0x54, 0x96, 0x71, 0x17, 0xf4, 0xcf, 0xac, 0x14, 0x86, 0x3a, 0x64,
	0x59, 0xe2, 0x67, 0xd0, 0x3a, 0x5d, 0xed, 0xd0, 0xec, 0xdf, 0xbd, 0xa0, 0x1a, 0x91, 0xd4, 0x93,
	0x8d, 0x47, 0xc8, 0xfd, 0xad, 0x83, 0x29, 0x3d, 0xfb, 0xcb, 0x64, 0xf0, 0x2d, 0xe8, 0x84, 0x51,
	0xc2, 0x0a, 0x4e, 0x93, 0x5c, 0x48, 0x19, 0x64, 0xbd, 0x80, 0x31, 0x18, 0xc7, 0x34, 0x91, 0x7a,
	0x5b, 0x44, 0xd4, 0xf8, 0x31, 0x18, 0x21, 0x9d, 0x16, 0x96, 0x2e, 0x1c, 0xdf, 0xfe, 0x7b, 0x0f,
	0xca, 0x70, 0x6f, 0xd9, 0x27, 0x2d, 0x0a, 0x04, 0x87, 0x75, 0x81, 0x5b, 0x86, 0x30, 0xe3, 0x36,
	0x98, 0x51, 0x3a, 0x07, 0x1a, 0xa9, 0xbb, 0x30, 0x9f, 0x9a, 0x03, 0xb2, 0xda, 0x62, 0x76, 0xef,
	0xa2, 0xb1, 0x0c, 0x34, 0xd2, 0x1c, 0xb6, 0x0f, 0x9b, 0x01, 0xe3, 0x74, 0x42, 0x39, 0xb5, 0x5a,
	0xc2, 0xfc, 0xbd, 0xff, 0x99, 0x3f, 0xeb, 0x95, 0x07, 0xb0, 0x42, 0xed, 0x87, 0xd0, 0x59, 0x9d,
	0x4b, 0x4d, 0xc6, 0x3b, 0x6a, 0xc6, 0x5b, 0x4a, 0x74, 0xf6, 0x53, 0xb8, 0x7a, 0x6e, 0xe6, 0x65,
	0xe0, 0x83, 0x2b, 0xd5, 0xe5, 0xde, 0x1f, 0xc0, 0xcd, 0xfa, 0xb7, 0x80, 0x77, 0xe1, 0x7a, 0xe0,
	0x87, 0xe4, 0xd5, 0xe1, 0x28, 0xfc, 0xf0, 0xd6, 0x1f, 0x1d, 0xbe, 0x19, 0x1e, 0x87, 0x3e, 0xe9,
	0x6a, 0xf8, 0x06, 0x5c, 0x53, 0x3f, 0x1c, 0x3d, 0x1f, 0x1e, 0xf9, 0x5d, 0x74, 0x60, 0x7f, 0x5b,
	0x38, 0xe8, 0xc7, 0xc2, 0x41, 0x3f, 0x17, 0x0e, 0xfa, 0xfa, 0xcb, 0xd1, 0x3e, 0x6e, 0x8a, 0x77,
	0x7e, 0x92, 0xc5, 0xe3, 0xb6, 0xa8, 0xee, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0xff, 0x37, 0x3f,
	0x5c, 0x07, 0x04, 0x00, 0x00,
}

func (m *UntypedSingleValue) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UntypedSingleValue) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UntypedSingleValue) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Value != 0 {
		i -= 8
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.Value))))
		i--
		dAtA[i] = 0x9
	}
	return len(dAtA) - i, nil
}

func (m *UntypedMultiDoubleValue) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UntypedMultiDoubleValue) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UntypedMultiDoubleValue) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Value != 0 {
		i -= 8
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.Value))))
		i--
		dAtA[i] = 0x11
	}
	if m.MetricType != 0 {
		i = encodeVarintMetricEvent(dAtA, i, uint64(m.MetricType))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *UntypedMultiDoubleValues) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UntypedMultiDoubleValues) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UntypedMultiDoubleValues) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Values) > 0 {
		for k := range m.Values {
			v := m.Values[k]
			baseI := i
			if v != nil {
				{
					size, err := v.MarshalToSizedBuffer(dAtA[:i])
					if err != nil {
						return 0, err
					}
					i -= size
					i = encodeVarintMetricEvent(dAtA, i, uint64(size))
				}
				i--
				dAtA[i] = 0x12
			}
			i -= len(k)
			copy(dAtA[i:], k)
			i = encodeVarintMetricEvent(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = encodeVarintMetricEvent(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *MetricEvent) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MetricEvent) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MetricEvent) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Value != nil {
		{
			size := m.Value.Size()
			i -= size
			if _, err := m.Value.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	if len(m.Metadata) > 0 {
		for k := range m.Metadata {
			v := m.Metadata[k]
			baseI := i
			if len(v) > 0 {
				i -= len(v)
				copy(dAtA[i:], v)
				i = encodeVarintMetricEvent(dAtA, i, uint64(len(v)))
				i--
				dAtA[i] = 0x12
			}
			i -= len(k)
			copy(dAtA[i:], k)
			i = encodeVarintMetricEvent(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = encodeVarintMetricEvent(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.Tags) > 0 {
		for k := range m.Tags {
			v := m.Tags[k]
			baseI := i
			if len(v) > 0 {
				i -= len(v)
				copy(dAtA[i:], v)
				i = encodeVarintMetricEvent(dAtA, i, uint64(len(v)))
				i--
				dAtA[i] = 0x12
			}
			i -= len(k)
			copy(dAtA[i:], k)
			i = encodeVarintMetricEvent(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = encodeVarintMetricEvent(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintMetricEvent(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if m.Timestamp != 0 {
		i = encodeVarintMetricEvent(dAtA, i, uint64(m.Timestamp))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MetricEvent_UntypedSingleValue) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MetricEvent_UntypedSingleValue) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.UntypedSingleValue != nil {
		{
			size, err := m.UntypedSingleValue.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMetricEvent(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	return len(dAtA) - i, nil
}
func (m *MetricEvent_UntypedMultiDoubleValues) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MetricEvent_UntypedMultiDoubleValues) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.UntypedMultiDoubleValues != nil {
		{
			size, err := m.UntypedMultiDoubleValues.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMetricEvent(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x32
	}
	return len(dAtA) - i, nil
}
func encodeVarintMetricEvent(dAtA []byte, offset int, v uint64) int {
	offset -= sovMetricEvent(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *UntypedSingleValue) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Value != 0 {
		n += 9
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *UntypedMultiDoubleValue) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MetricType != 0 {
		n += 1 + sovMetricEvent(uint64(m.MetricType))
	}
	if m.Value != 0 {
		n += 9
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *UntypedMultiDoubleValues) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Values) > 0 {
		for k, v := range m.Values {
			_ = k
			_ = v
			l = 0
			if v != nil {
				l = v.Size()
				l += 1 + sovMetricEvent(uint64(l))
			}
			mapEntrySize := 1 + len(k) + sovMetricEvent(uint64(len(k))) + l
			n += mapEntrySize + 1 + sovMetricEvent(uint64(mapEntrySize))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *MetricEvent) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Timestamp != 0 {
		n += 1 + sovMetricEvent(uint64(m.Timestamp))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovMetricEvent(uint64(l))
	}
	if len(m.Tags) > 0 {
		for k, v := range m.Tags {
			_ = k
			_ = v
			l = 0
			if len(v) > 0 {
				l = 1 + len(v) + sovMetricEvent(uint64(len(v)))
			}
			mapEntrySize := 1 + len(k) + sovMetricEvent(uint64(len(k))) + l
			n += mapEntrySize + 1 + sovMetricEvent(uint64(mapEntrySize))
		}
	}
	if m.Value != nil {
		n += m.Value.Size()
	}
	if len(m.Metadata) > 0 {
		for k, v := range m.Metadata {
			_ = k
			_ = v
			l = 0
			if len(v) > 0 {
				l = 1 + len(v) + sovMetricEvent(uint64(len(v)))
			}
			mapEntrySize := 1 + len(k) + sovMetricEvent(uint64(len(k))) + l
			n += mapEntrySize + 1 + sovMetricEvent(uint64(mapEntrySize))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *MetricEvent_UntypedSingleValue) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.UntypedSingleValue != nil {
		l = m.UntypedSingleValue.Size()
		n += 1 + l + sovMetricEvent(uint64(l))
	}
	return n
}
func (m *MetricEvent_UntypedMultiDoubleValues) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.UntypedMultiDoubleValues != nil {
		l = m.UntypedMultiDoubleValues.Size()
		n += 1 + l + sovMetricEvent(uint64(l))
	}
	return n
}

func sovMetricEvent(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMetricEvent(x uint64) (n int) {
	return sovMetricEvent(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *UntypedSingleValue) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMetricEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UntypedSingleValue: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UntypedSingleValue: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.Value = float64(math.Float64frombits(v))
		default:
			iNdEx = preIndex
			skippy, err := skipMetricEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMetricEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UntypedMultiDoubleValue) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMetricEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UntypedMultiDoubleValue: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UntypedMultiDoubleValue: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MetricType", wireType)
			}
			m.MetricType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetricEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MetricType |= UntypedValueMetricType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.Value = float64(math.Float64frombits(v))
		default:
			iNdEx = preIndex
			skippy, err := skipMetricEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMetricEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UntypedMultiDoubleValues) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMetricEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UntypedMultiDoubleValues: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UntypedMultiDoubleValues: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Values", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetricEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMetricEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMetricEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Values == nil {
				m.Values = make(map[string]*UntypedMultiDoubleValue)
			}
			var mapkey string
			var mapvalue *UntypedMultiDoubleValue
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowMetricEvent
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowMetricEvent
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthMetricEvent
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthMetricEvent
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var mapmsglen int
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowMetricEvent
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapmsglen |= int(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					if mapmsglen < 0 {
						return ErrInvalidLengthMetricEvent
					}
					postmsgIndex := iNdEx + mapmsglen
					if postmsgIndex < 0 {
						return ErrInvalidLengthMetricEvent
					}
					if postmsgIndex > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = &UntypedMultiDoubleValue{}
					if err := mapvalue.Unmarshal(dAtA[iNdEx:postmsgIndex]); err != nil {
						return err
					}
					iNdEx = postmsgIndex
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipMetricEvent(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthMetricEvent
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Values[mapkey] = mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMetricEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMetricEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MetricEvent) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMetricEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MetricEvent: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MetricEvent: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			m.Timestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetricEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Timestamp |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetricEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMetricEvent
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMetricEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = append(m.Name[:0], dAtA[iNdEx:postIndex]...)
			if m.Name == nil {
				m.Name = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tags", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetricEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMetricEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMetricEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Tags == nil {
				m.Tags = make(map[string][]byte)
			}
			var mapkey string
			mapvalue := []byte{}
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowMetricEvent
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowMetricEvent
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthMetricEvent
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthMetricEvent
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var mapbyteLen uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowMetricEvent
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapbyteLen |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intMapbyteLen := int(mapbyteLen)
					if intMapbyteLen < 0 {
						return ErrInvalidLengthMetricEvent
					}
					postbytesIndex := iNdEx + intMapbyteLen
					if postbytesIndex < 0 {
						return ErrInvalidLengthMetricEvent
					}
					if postbytesIndex > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = make([]byte, mapbyteLen)
					copy(mapvalue, dAtA[iNdEx:postbytesIndex])
					iNdEx = postbytesIndex
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipMetricEvent(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthMetricEvent
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Tags[mapkey] = mapvalue
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UntypedSingleValue", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetricEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMetricEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMetricEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &UntypedSingleValue{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Value = &MetricEvent_UntypedSingleValue{v}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Metadata", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetricEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMetricEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMetricEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Metadata == nil {
				m.Metadata = make(map[string][]byte)
			}
			var mapkey string
			mapvalue := []byte{}
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowMetricEvent
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowMetricEvent
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthMetricEvent
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthMetricEvent
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var mapbyteLen uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowMetricEvent
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapbyteLen |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intMapbyteLen := int(mapbyteLen)
					if intMapbyteLen < 0 {
						return ErrInvalidLengthMetricEvent
					}
					postbytesIndex := iNdEx + intMapbyteLen
					if postbytesIndex < 0 {
						return ErrInvalidLengthMetricEvent
					}
					if postbytesIndex > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = make([]byte, mapbyteLen)
					copy(mapvalue, dAtA[iNdEx:postbytesIndex])
					iNdEx = postbytesIndex
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipMetricEvent(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthMetricEvent
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Metadata[mapkey] = mapvalue
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UntypedMultiDoubleValues", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetricEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMetricEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMetricEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &UntypedMultiDoubleValues{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Value = &MetricEvent_UntypedMultiDoubleValues{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMetricEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMetricEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMetricEvent(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMetricEvent
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMetricEvent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMetricEvent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMetricEvent
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMetricEvent
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMetricEvent
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMetricEvent        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMetricEvent          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMetricEvent = fmt.Errorf("proto: unexpected end of group")
)
