// Copyright 2026 iLogtail Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package selfmonitor

type AlarmType string

func (a AlarmType) String() string {
	return string(a)
}

// isTypedAlarmType limits logger alarm types to selfmonitor.AlarmType.
func (a AlarmType) isTypedAlarmType() {}

type TypedAlarmType interface {
	isTypedAlarmType()
	String() string
}

const (
	AggGroupAlarm                       AlarmType = "AGG_GROUP_ALARM"
	AggShardhashNotFoundKey             AlarmType = "AGG_SHARDHASH_NOT_FOUND_KEY"
	AggregateOversizeAlarm              AlarmType = "AGGREGATE_OVERSIZE_ALARM"
	AggregatorAddAlarm                  AlarmType = "AGGREGATOR_ADD_ALARM"
	AggregatorInitErrorAlarm            AlarmType = "AGGREGATOR_INIT_ERROR"
	AnchorFindAlarm                     AlarmType = "ANCHOR_FIND_ALARM"
	AnchorJSONAlarm                     AlarmType = "ANCHOR_JSON_ALARM"
	AsyncExecFailed                     AlarmType = "ASYNC_EXEC_FAILED"
	Base64DAlarm                        AlarmType = "BASE64_D_ALARM"
	Base64DFindAlarm                    AlarmType = "BASE64_D_FIND_ALARM"
	Base64EFindAlarm                    AlarmType = "BASE64_E_FIND_ALARM"
	BootInitAlarm                       AlarmType = "BOOT_INIT_ALARM"
	BootLoadAlarm                       AlarmType = "BOOT_LOAD_ALARM"
	BootStartAlarm                      AlarmType = "BOOT_START_ALARM"
	BootStopAlarm                       AlarmType = "BOOT_STOP_ALARM"
	CadvisorComposeAlarm                AlarmType = "CADVISOR_COMPOSE_ALARM"
	CanalInvalidAlarm                   AlarmType = "CANAL_INVALID_ALARM"
	CanalRuntimeAlarm                   AlarmType = "CANAL_RUNTIME_ALARM"
	CanalStartAlarm                     AlarmType = "CANAL_START_ALARM"
	CatchStandardOutputAlarm            AlarmType = "CATCH_STANDARD_OUTPUT_ALARM"
	CategoryConfigAlarm                 AlarmType = "CATEGORY_CONFIG_ALARM"
	CheckpointAlarm                     AlarmType = "CHECKPOINT_ALARM"
	CheckpointGetAlarm                  AlarmType = "CHECKPOINT_GET_ALARM"
	CheckpointInitAlarm                 AlarmType = "CHECKPOINT_INIT_ALARM"
	CheckpointInvalidAlarm              AlarmType = "CHECKPOINT_INVALID_ALARM"
	CheckpointSaveAlarm                 AlarmType = "CHECKPOINT_SAVE_ALARM"
	ClickhouseSubscriberAlarm           AlarmType = "CLICKHOUSE_SUBSCRIBER_ALARM"
	CloudMetaAlarm                      AlarmType = "CLOUD_META_ALARM"
	CompileRegexpAlarm                  AlarmType = "COMPILE_REGEXP_ALARM"
	ConditionInitAlarm                  AlarmType = "CONDITION_INIT_ALARM"
	ConfigLoadAlarm                     AlarmType = "CONFIG_LOAD_ALARM"
	ConfigStopTimeoutAlarm              AlarmType = "CONFIG_STOP_TIMEOUT_ALARM"
	ConnectCriRuntimeAlarm              AlarmType = "CONNECT_CRI_RUNTIME_ALARM"
	ContainerCenterAlarm                AlarmType = "CONTAINER_CENTER_ALARM"
	ContainerdClientAlarm               AlarmType = "CONTAINERD_CLIENT_ALARM"
	ConvertAlarm                        AlarmType = "CONVERT_ALARM"
	CopyLogAlarm                        AlarmType = "COPY_LOG_ALARM"
	CreateContainerdInfoAlarm           AlarmType = "CREATE_CONTAINERD_INFO_ALARM"
	DecodeBodyFailAlarm                 AlarmType = "DECODE_BODY_FAIL_ALARM"
	DecodeFindAlarm                     AlarmType = "DECODE_FIND_ALARM"
	DecodeLogAlarm                      AlarmType = "DECODE_LOG_ALARM"
	DecodeMessageFailAlarm              AlarmType = "DECODE_MESSAGE_FAIL_ALARM"
	DefaultFlusherAlarm                 AlarmType = "DEFAULT_FLUSHER_ALARM"
	DetectContainerAlarm                AlarmType = "DETECT_CONTAINER_ALARM"
	DockerCenterAlarm                   AlarmType = "DOCKER_CENTER_ALARM"
	DockerClientAlarm                   AlarmType = "DOCKER_CLIENT_ALARM"
	DockerEventAlarm                    AlarmType = "DOCKER_EVENT_ALARM"
	DockerExecAlarm                     AlarmType = "DOCKER_EXEC_ALARM"
	DockerMatchAlarm                    AlarmType = "DOCKER_MATCH_ALARM"
	DockerRegexCompileAlarm             AlarmType = "DOCKER_REGEX_COMPILE_ALARM"
	DockerStdoutStartAlarm              AlarmType = "DOCKER_STDOUT_START_ALARM"
	DockerStdoutStatAlarm               AlarmType = "DOCKER_STDOUT_STAT_ALARM"
	DockerStdoutStopAlarm               AlarmType = "DOCKER_STDOUT_STOP_ALARM"
	DorisSubscriberAlarm                AlarmType = "DORIS_SUBSCRIBER_ALARM"
	DownDockerComposeError              AlarmType = "DOWN_DOCKER_COMPOSE_ERROR"
	DropDataAlarm                       AlarmType = "DROP_DATA_ALARM"
	DumpFileAlarm                       AlarmType = "DUMP_FILE_ALARM"
	ECSAlarm                            AlarmType = "ECS_ALARM"
	ElasticsearchSubscriberAlarm        AlarmType = "ELASTICSEARCH_SUBSCRIBER_ALARM"
	EnvFlagAlarm                        AlarmType = "ENV_FLAG_ALARM"
	ErrorJMXPort                        AlarmType = "ERROR_JMX_PORT"
	ExecAlarm                           AlarmType = "EXEC_ALARM"
	ExportReqFailAlarm                  AlarmType = "EXPORT_REQ_FAIL_ALARM"
	ExtensionFilterAlarm                AlarmType = "EXTENSION_FILTER_ALARM"
	FailToInitPing                      AlarmType = "FAIL_TO_INIT_PING"
	FailToRunHttping                    AlarmType = "FAIL_TO_RUN_HTTPING"
	FailToRunPing                       AlarmType = "FAIL_TO_RUN_PING"
	FailedCollectHostMetadata           AlarmType = "FAILED_COLLECT_HOST_METADATA"
	FilenrPatternAlarm                  AlarmType = "FILENR_PATTERN_ALARM"
	FilterInitAlarm                     AlarmType = "FILTER_INIT_ALARM"
	FlushDataAlarm                      AlarmType = "FLUSH_DATA_ALARM"
	FlusherFlushAlarm                   AlarmType = "FLUSHER_FLUSH_ALARM"
	FlusherFlushAlram                   AlarmType = "FLUSHER_FLUSH_ALRAM"
	FlusherInitAlarm                    AlarmType = "FLUSHER_INIT_ALARM"
	FlusherQueueFull                    AlarmType = "FLUSHER_QUEUE_FULL"
	FlusherReadyAlarm                   AlarmType = "FLUSHER_READY_ALARM"
	FlusherStopAlarm                    AlarmType = "FLUSHER_STOP_ALARM"
	GPUNVMLCollectAlarm                 AlarmType = "GPU_NVML_COLLECT_ALARM"
	GPUNVMLDeviceCountAlarm             AlarmType = "GPU_NVML_DEVICE_COUNT_ALARM"
	GPUNVMLDeviceIndexAlarm             AlarmType = "GPU_NVML_DEVICE_INDEX_ALARM"
	GPUNVMLInitAlarm                    AlarmType = "GPU_NVML_INIT_ALARM"
	GRPCFlushAlarm                      AlarmType = "GRPC_FLUSH_ALARM"
	GRPCFlusherAlarm                    AlarmType = "GRPC_FLUSHER_ALARM"
	GRPCServerAlarm                     AlarmType = "GRPC_SERVER_ALARM"
	GeoipAlarm                          AlarmType = "GEOIP_ALARM"
	GetSigmaEnvError                    AlarmType = "GET_SIGMA_ENV_ERROR"
	GoprofileAlarm                      AlarmType = "GOPROFILE_ALARM"
	GotimeFindAlarm                     AlarmType = "GOTIME_FIND_ALARM"
	GotimeParseAlarm                    AlarmType = "GOTIME_PARSE_ALARM"
	GrokFindAlarm                       AlarmType = "GROK_FIND_ALARM"
	HTTPCollectAlarm                    AlarmType = "HTTP_COLLECT_ALARM"
	HTTPInitAlarm                       AlarmType = "HTTP_INIT_ALARM"
	HTTPLoadAddressAlarm                AlarmType = "HTTP_LOAD_ADDRESS_ALARM"
	HTTPParseAlarm                      AlarmType = "HTTP_PARSE_ALARM"
	HTTPServerError                     AlarmType = "HTTP_SERVER_ERROR"
	HoldonLogtailpluginAlarm            AlarmType = "HOLDON_LOGTAILPLUGIN_ALARM"
	InfluxdbSubscriberAlarm             AlarmType = "INFLUXDB_SUBSCRIBER_ALARM"
	InitAlarm                           AlarmType = "INIT_ALARM"
	InitCatchStderrAlarm                AlarmType = "INIT_CATCH_STDERR_ALARM"
	InitCatchStdoutAlarm                AlarmType = "INIT_CATCH_STDOUT_ALARM"
	InitCheckpointAlarm                 AlarmType = "INIT_CHECKPOINT_ALARM"
	InitHTTPServerAlarm                 AlarmType = "INIT_HTTP_SERVER_ALARM"
	InitServerArmar                     AlarmType = "INIT_SERVER_ARMAR"
	InputCanalAlarm                     AlarmType = "INPUT_CANAL_ALARM"
	InputCollectAlarm                   AlarmType = "INPUT_COLLECT_ALARM"
	InputKafkaAlarm                     AlarmType = "INPUT_KAFKA_ALARM"
	InputSnmpConnectionError            AlarmType = "INPUT_SNMP_CONNECTION_ERROR"
	InvalidAggregatorTypeAlarm          AlarmType = "INVALID_AGGREGATOR_TYPE"
	InvalidKafkaPartitioner             AlarmType = "INVALID_KAFKA_PARTITIONER"
	InvalidProcessorTypeAlarm           AlarmType = "INVALID_PROCESSOR_TYPE"
	InvalidRegexAlarm                   AlarmType = "INVALID_REGEX_ALARM"
	JmxfetchAlarm                       AlarmType = "JMXFETCH_ALARM"
	JmxfetchRuntimeAlarm                AlarmType = "JMXFETCH_RUNTIME_ALARM"
	JournalReadAlarm                    AlarmType = "JOURNAL_READ_ALARM"
	JournalSeekAlarm                    AlarmType = "JOURNAL_SEEK_ALARM"
	K8sMetaCollectorError               AlarmType = "K8S_META_COLLECTOR_ERROR"
	KafkaSubscriberAlarm                AlarmType = "KAFKA_SUBSCRIBER_ALARM"
	KubePrometheusAlarm                 AlarmType = "KUBE_PROMETHEUS_ALARM"
	KubernetesLabelSelectorError        AlarmType = "KUBERNETES_LABEL_SELECTOR_ERROR"
	KubernetesMetaAlarm                 AlarmType = "KUBERNETES_META_ALARM"
	KubernetesMetaCollectError          AlarmType = "KUBERNETES_META_COLLECT_ERROR"
	KubernetesMetaFetchIntervalAlarm    AlarmType = "KUBERNETES_META_FETCH_INTERVAL_ALARM"
	KvSplitterAlarm                     AlarmType = "KV_SPLITTER_ALARM"
	ListHistoryDumpAlarm                AlarmType = "LIST_HISTORY_DUMP_ALARM"
	LoadConfigAlarm                     AlarmType = "LOAD_CONFIG_ALARM"
	LoadPluginAlarm                     AlarmType = "LOAD_PLUGIN_ALARM"
	LogRegexFindAlarm                   AlarmType = "LOG_REGEX_FIND_ALARM"
	LoongcollectorComposeAlarm          AlarmType = "LOONGCOLLECTOR_COMPOSE_ALARM"
	LumberConnectionAlarm               AlarmType = "LUMBER_CONNECTION_ALARM"
	LumberListenAlarm                   AlarmType = "LUMBER_LISTEN_ALARM"
	MD5FindAlarm                        AlarmType = "MD5_FIND_ALARM"
	MarshalRespFailAlarm                AlarmType = "MARSHAL_RESP_FAIL_ALARM"
	MetricInputV2StartFailureAlarm      AlarmType = "METRIC_INPUT_V2_START_FAILURE"
	MonitorStartAlarm                   AlarmType = "MONITOR_START_ALARM"
	MonitorTimeoutAlarm                 AlarmType = "MONITOR_TIMEOUT_ALARM"
	MqttConnectAlarm                    AlarmType = "MQTT_CONNECT_ALARM"
	MqttConnectionLostAlarm             AlarmType = "MQTT_CONNECTION_LOST_ALARM"
	MqttSubscribeAlarm                  AlarmType = "MQTT_SUBSCRIBE_ALARM"
	MultiHTTPServerAlarm                AlarmType = "MULTI_HTTP_SERVER_ALARM"
	MysqlCheckpoingAlarm                AlarmType = "MYSQL_CHECKPOING_ALARM"
	MysqlCheckpointAlarm                AlarmType = "MYSQL_CHECKPOINT_ALARM"
	MysqlInitAlarm                      AlarmType = "MYSQL_INIT_ALARM"
	MysqlParseAlarm                     AlarmType = "MYSQL_PARSE_ALARM"
	MysqlQueryAlarm                     AlarmType = "MYSQL_QUERY_ALARM"
	MysqlTimeoutAlarm                   AlarmType = "MYSQL_TIMEOUT_ALARM"
	NginxStatusCollectAlarm             AlarmType = "NGINX_STATUS_COLLECT_ALARM"
	NginxStatusInitAlarm                AlarmType = "NGINX_STATUS_INIT_ALARM"
	NoMatchRouterAlarm                  AlarmType = "NO_MATCH_ROUTER_ALARM"
	Open1mountsAlarm                    AlarmType = "OPEN_1MOUNTS_ALARM"
	OpenFilenrAlarm                     AlarmType = "OPEN_FILENR_ALARM"
	OpenProcfsAlarm                     AlarmType = "OPEN_PROCFS_ALARM"
	PackJSONAlarm                       AlarmType = "PACK_JSON_ALARM"
	ParseDockerLineAlarm                AlarmType = "PARSE_DOCKER_LINE_ALARM"
	PathAlarm                           AlarmType = "PATH_ALARM"
	PluginAlarm                         AlarmType = "PLUGIN_ALARM"
	PluginRunAlarm                      AlarmType = "PLUGIN_RUN_ALARM"
	PluginRuntimeAlarm                  AlarmType = "PLUGIN_RUNTIME_ALARM"
	PluginUnmarshalAlarm                AlarmType = "PLUGIN_UNMARSHAL_ALARM"
	PprofProfileAlarm                   AlarmType = "PPROF_PROFILE_ALARM"
	ProcessLabelTooLongAlarm            AlarmType = "PROCESS_LABEL_TOO_LONG_ALARM"
	ProcessListAlarm                    AlarmType = "PROCESS_LIST_ALARM"
	ProcessorDesensitizeAlarm           AlarmType = "PROCESSOR_DESENSITIZE_ALARM"
	ProcessorEncryptAlarm               AlarmType = "PROCESSOR_ENCRYPT_ALARM"
	ProcessorInitAlarm                  AlarmType = "PROCESSOR_INIT_ALARM"
	ProcessorJSONFindAlarm              AlarmType = "PROCESSOR_JSON_FIND_ALARM"
	ProcessorJSONParserAlarm            AlarmType = "PROCESSOR_JSON_PARSER_ALARM"
	ProcessorOTELMetricDataFormat       AlarmType = "PROCESSOR_OTEL_METRIC_DATA_FORMAT"
	ProcessorOTELMetricFindAlarm        AlarmType = "PROCESSOR_OTEL_METRIC_FIND_ALARM"
	ProcessorOTELMetricParserAlarm      AlarmType = "PROCESSOR_OTEL_METRIC_PARSER_ALARM"
	ProcessorOTELTraceDataFormat        AlarmType = "PROCESSOR_OTEL_TRACE_DATA_FORMAT"
	ProcessorOTELTraceFindAlarm         AlarmType = "PROCESSOR_OTEL_TRACE_FIND_ALARM"
	ProcessorOTELTraceParserAlarm       AlarmType = "PROCESSOR_OTEL_TRACE_PARSER_ALARM"
	ProcessorSplitLogStringFindAlarm    AlarmType = "PROCESSOR_SPLIT_LOG_STRING_FIND_ALARM"
	ProcessorStringReplaceAlarm         AlarmType = "PROCESSOR_STRING_REPLACE_ALARM"
	PrometheusFlusherInitAlarm          AlarmType = "PROMETHEUS_FLUSHER_INIT_ALARM"
	PyroscopeAlarm                      AlarmType = "PYROSCOPE_ALARM"
	Read1mountsAlarm                    AlarmType = "READ_1MOUNTS_ALARM"
	ReadBodyFailAlarm                   AlarmType = "READ_BODY_FAIL_ALARM"
	ReadDiskAlarm                       AlarmType = "READ_DISK_ALARM"
	ReadFileAlarm                       AlarmType = "READ_FILE_ALARM"
	ReadFilenrAlarm                     AlarmType = "READ_FILENR_ALARM"
	ReadProcAlarm                       AlarmType = "READ_PROC_ALARM"
	ReadPtoctcp6Alarm                   AlarmType = "READ_PTOCTCP6_ALARM"
	ReadPtoctcpAlarm                    AlarmType = "READ_PTOCTCP_ALARM"
	ReadStaticConfigAlarm               AlarmType = "READ_STATIC_CONFIG_ALARM"
	ReceiveLogGroupAlarm                AlarmType = "RECEIVE_LOG_GROUP_ALARM"
	ReceiveRawLogAlarm                  AlarmType = "RECEIVE_RAW_LOG_ALARM"
	RedisCollectAlarm                   AlarmType = "REDIS_COLLECT_ALARM"
	RedisParseAddressAlarm              AlarmType = "REDIS_PARSE_ADDRESS_ALARM"
	RegexCompileAlarm                   AlarmType = "REGEX_COMPILE_ALARM"
	RegexFindAlarm                      AlarmType = "REGEX_FIND_ALARM"
	RegexUnmatchedAlarm                 AlarmType = "REGEX_UNMATCHED_ALARM"
	RenameFindAlarm                     AlarmType = "RENAME_FIND_ALARM"
	RuntimeAlarm                        AlarmType = "RUNTIME_ALARM"
	SaveCheckpointAlarm                 AlarmType = "SAVE_CHECKPOINT_ALARM"
	ServiceOTLPInvalidGRPCServerConfig  AlarmType = "SERVICE_OTLP_INVALID_GRPC_SERVER_CONFIG"
	ServiceSyslogCloseAlarm             AlarmType = "SERVICE_SYSLOG_CLOSE_ALARM"
	ServiceSyslogInitAlarm              AlarmType = "SERVICE_SYSLOG_INIT_ALARM"
	ServiceSyslogPacketAlarm            AlarmType = "SERVICE_SYSLOG_PACKET_ALARM"
	ServiceSyslogParseAlarm             AlarmType = "SERVICE_SYSLOG_PARSE_ALARM"
	ServiceSyslogRsyslogConfigAlarm     AlarmType = "SERVICE_SYSLOG_RSYSLOG_CONFIG_ALARM"
	ServiceSyslogRsyslogRestartAlarm    AlarmType = "SERVICE_SYSLOG_RSYSLOG_RESTART_ALARM"
	ServiceSyslogStreamAlarm            AlarmType = "SERVICE_SYSLOG_STREAM_ALARM"
	ServiceTelegrafOverwriteConfigAlarm AlarmType = "SERVICE_TELEGRAF_OVERWRITE_CONFIG_ALARM"
	ServiceTelegrafRemoveConfigAlarm    AlarmType = "SERVICE_TELEGRAF_REMOVE_CONFIG_ALARM"
	ServiceTelegrafRuntimeAlarm         AlarmType = "SERVICE_TELEGRAF_RUNTIME_ALARM"
	SkywalkingCollectTraceError         AlarmType = "SKYWALKING_COLLECT_TRACE_ERROR"
	SkywalkingLoadCheckpointFail        AlarmType = "SKYWALKING_LOAD_CHECKPOINT_FAIL"
	SkywalkingMeterGRPCError            AlarmType = "SKYWALKING_METER_GRPC_ERROR"
	SkywalkingResourceNotReady          AlarmType = "SKYWALKING_RESOURCE_NOT_READY"
	SkywalkingSaveCheckpointFail        AlarmType = "SKYWALKING_SAVE_CHECKPOINT_FAIL"
	SkywalkingToOtTraceErr              AlarmType = "SKYWALKING_TO_OT_TRACE_ERR"
	SkywalkingTopicNotRecognized        AlarmType = "SKYWALKING_TOPIC_NOT_RECOGNIZED"
	SplitFindAlarm                      AlarmType = "SPLIT_FIND_ALARM"
	SplitLogAlarm                       AlarmType = "SPLIT_LOG_ALARM"
	StartDockerComposeError             AlarmType = "START_DOCKER_COMPOSE_ERROR"
	StartPluginAlarm                    AlarmType = "START_PLUGIN_ALARM"
	StatFileAlarm                       AlarmType = "STAT_FILE_ALARM"
	StatsdParseAlarm                    AlarmType = "STATSD_PARSE_ALARM"
	StderrAlarm                         AlarmType = "STDERR_ALARM"
	StopDockerComposeError              AlarmType = "STOP_DOCKER_COMPOSE_ERROR"
	StopExtensionAlarm                  AlarmType = "STOP_EXTENSION_ALARM"
	StopFlusherAlarm                    AlarmType = "STOP_FLUSHER_ALARM"
	StrptimeParseAlarm                  AlarmType = "STRPTIME_PARSE_ALARM"
	SyncContainerdAlarm                 AlarmType = "SYNC_CONTAINERD_ALARM"
	TaskExecuteSlowAlarm                AlarmType = "TASK_EXECUTE_SLOW"
	TelegrafAlarm                       AlarmType = "TELEGRAF_ALARM"
	UDPServerAlarm                      AlarmType = "UDP_SERVER_ALARM"
	WineventlogApiAlarm                 AlarmType = "WINEVENTLOG_API_ALARM"
	WineventlogMainAlarm                AlarmType = "WINEVENTLOG_MAIN_ALARM"
	WineventlogUtilAlarm                AlarmType = "WINEVENTLOG_UTIL_ALARM"
	WrongProtobufAlarm                  AlarmType = "WRONG_PROTOBUF_ALARM"
)
