// Copyright 2026 iLogtail Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package dockercompose

import (
	"bytes"
	"context"
	"fmt"
	"net"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"gopkg.in/yaml.v3"
)

const (
	composePortTimeout       = 60 * time.Second
	composePortRetryInterval = 500 * time.Millisecond
	composeStartupTimeout    = 10 * time.Minute
	dockerCommandTimeout     = 2 * time.Minute
)

type composePort struct {
	service     string
	privatePort string
	virtual     string
}

func runComposeCommand(ctx context.Context, composeFile, projectName string, command ...string) (string, error) {
	if _, err := exec.LookPath("docker-compose"); err == nil {
		args := []string{"-f", composeFile, "-p", projectName}
		args = append(args, command...)
		return runCommand(ctx, "docker-compose", args...)
	}
	args := []string{"compose", "-f", composeFile, "-p", projectName}
	args = append(args, command...)
	return runDockerCommand(ctx, args...)
}

func runComposeCommandWithTimeout(
	ctx context.Context,
	timeout time.Duration,
	composeFile,
	projectName string,
	command ...string,
) error {
	commandCtx, cancel := context.WithTimeout(ctx, timeout)
	defer cancel()
	_, err := runComposeCommand(commandCtx, composeFile, projectName, command...)
	return err
}

func runDockerCommand(ctx context.Context, args ...string) (string, error) {
	return runCommand(ctx, "docker", args...)
}

func runDockerCommandWithTimeout(
	ctx context.Context,
	timeout time.Duration,
	args ...string,
) (string, error) {
	commandCtx, cancel := context.WithTimeout(ctx, timeout)
	defer cancel()
	return runDockerCommand(commandCtx, args...)
}

func runCommand(ctx context.Context, executable string, args ...string) (string, error) {
	var stdout bytes.Buffer
	var stderr bytes.Buffer
	cmd := exec.CommandContext(ctx, executable, args...)
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr
	if err := cmd.Run(); err != nil {
		output := strings.TrimSpace(strings.Join([]string{stdout.String(), stderr.String()}, "\n"))
		if ctx.Err() != nil {
			return strings.TrimSpace(stdout.String()),
				fmt.Errorf("%s %s failed: %w; output: %s", executable, strings.Join(args, " "), ctx.Err(), output)
		}
		return strings.TrimSpace(stdout.String()),
			fmt.Errorf("%s %s failed: %w; output: %s", executable, strings.Join(args, " "), err, output)
	}
	return strings.TrimSpace(stdout.String()), nil
}

func loadComposePorts(composeFile string) ([]composePort, error) {
	// composeFile is generated by the E2E harness under the configured case directory.
	data, err := os.ReadFile(filepath.Clean(composeFile)) // #nosec G304
	if err != nil {
		return nil, fmt.Errorf("read compose file %q: %w", composeFile, err)
	}
	var cfg struct {
		Services map[string]struct {
			Ports []interface{} `yaml:"ports"`
		} `yaml:"services"`
	}
	if err = yaml.Unmarshal(data, &cfg); err != nil {
		return nil, fmt.Errorf("parse compose file %q: %w", composeFile, err)
	}

	var ports []composePort
	for service, serviceCfg := range cfg.Services {
		for i, rawPort := range serviceCfg.Ports {
			port, parseErr := parseComposePort(service, rawPort)
			if parseErr != nil {
				return nil, fmt.Errorf("parse service %q port %d: %w", service, i, parseErr)
			}
			ports = append(ports, port)
		}
	}
	return ports, nil
}

func parseComposePort(service string, rawPort interface{}) (composePort, error) {
	var value string
	switch port := rawPort.(type) {
	case int:
		value = strconv.Itoa(port)
	case string:
		value = strings.TrimSpace(port)
	case map[string]interface{}:
		target, ok := port["target"]
		if !ok {
			return composePort{}, fmt.Errorf("long syntax port has no target")
		}
		switch target := target.(type) {
		case int:
			value = strconv.Itoa(target)
		case string:
			value = strings.TrimSpace(target)
		default:
			return composePort{}, fmt.Errorf("unsupported target port type %T", target)
		}
		if protocol, ok := port["protocol"]; ok {
			protocolValue, ok := protocol.(string)
			if !ok {
				return composePort{}, fmt.Errorf("unsupported port protocol type %T", protocol)
			}
			value += "/" + strings.TrimSpace(protocolValue)
		}
	default:
		return composePort{}, fmt.Errorf("unsupported port type %T", rawPort)
	}

	target := value
	if separator := strings.LastIndex(target, ":"); separator >= 0 {
		target = target[separator+1:]
	}
	parts := strings.Split(target, "/")
	if len(parts) > 2 {
		return composePort{}, fmt.Errorf("invalid target port %q", target)
	}
	portNumber, err := strconv.Atoi(parts[0])
	if err != nil || portNumber < 1 || portNumber > 65535 {
		return composePort{}, fmt.Errorf("invalid target port %q", target)
	}
	protocol := "tcp"
	if len(parts) == 2 {
		protocol = strings.ToLower(parts[1])
		if protocol != "tcp" && protocol != "udp" {
			return composePort{}, fmt.Errorf("unsupported port protocol %q", protocol)
		}
	}
	port := strconv.Itoa(portNumber)
	return composePort{
		service:     service,
		privatePort: port + "/" + protocol,
		virtual:     service + ":" + port,
	}, nil
}

func registerComposePortMappings(ctx context.Context, composeFile, projectName string) error {
	ports, err := loadComposePorts(composeFile)
	if err != nil {
		return err
	}
	for _, port := range ports {
		physical, mapErr := waitForComposePort(ctx, composeFile, projectName, port)
		if mapErr != nil {
			return mapErr
		}
		registerNetMapping(port.virtual, physical)
	}
	return nil
}

func waitForComposePort(ctx context.Context, composeFile, projectName string, port composePort) (string, error) {
	retryCtx, cancel := context.WithTimeout(ctx, composePortTimeout)
	defer cancel()

	command, err := composePortCommand(port)
	if err != nil {
		return "", err
	}
	var lastErr error
	for {
		output, err := runComposeCommand(retryCtx, composeFile, projectName, command...)
		if err == nil {
			if output == "" {
				err = fmt.Errorf("docker compose port returned empty output")
			} else {
				physical, parseErr := parseComposePortOutput(output)
				if parseErr == nil {
					if strings.HasSuffix(port.privatePort, "/udp") {
						return physical, nil
					}
					conn, dialErr := net.DialTimeout("tcp", physical, composePortRetryInterval)
					if dialErr == nil {
						_ = conn.Close()
						return physical, nil
					}
					err = fmt.Errorf("mapped port %s is not accepting TCP connections: %w", physical, dialErr)
				} else {
					err = parseErr
				}
			}
		}
		lastErr = err

		select {
		case <-retryCtx.Done():
			return "", fmt.Errorf(
				"resolve compose port for service %q port %q within %s: %w; last error: %v",
				port.service,
				port.privatePort,
				composePortTimeout,
				retryCtx.Err(),
				lastErr,
			)
		case <-time.After(composePortRetryInterval):
		}
	}
}

func composePortCommand(port composePort) ([]string, error) {
	portNumber, protocol, ok := strings.Cut(port.privatePort, "/")
	if !ok {
		return nil, fmt.Errorf("invalid private port %q", port.privatePort)
	}
	return []string{"port", "--protocol", protocol, port.service, portNumber}, nil
}

func parseComposePortOutput(output string) (string, error) {
	for _, line := range strings.Split(output, "\n") {
		address := strings.TrimSpace(line)
		if address == "" {
			continue
		}
		host, port, err := net.SplitHostPort(address)
		if err != nil {
			return "", fmt.Errorf("parse docker compose port output %q: %w", address, err)
		}
		switch host {
		case "", "0.0.0.0", "::":
			host = "127.0.0.1"
		}
		return net.JoinHostPort(host, port), nil
	}
	return "", fmt.Errorf("docker compose port returned no address")
}

func findSingleContainer(ctx context.Context, nameFilters ...string) (string, error) {
	args := []string{"ps", "--format", "{{.ID}}"}
	for _, nameFilter := range nameFilters {
		args = append(args, "--filter", "name="+nameFilter)
	}
	output, err := runDockerCommand(ctx, args...)
	if err != nil {
		return "", fmt.Errorf("find container with name filters %q: %w", nameFilters, err)
	}
	ids := strings.Fields(output)
	if len(ids) != 1 {
		return "", fmt.Errorf("container count for name filters %q is %d, want 1", nameFilters, len(ids))
	}
	return ids[0], nil
}

func execInContainer(id string, command []string) error {
	ctx, cancel := context.WithTimeout(context.Background(), dockerCommandTimeout)
	defer cancel()

	args := []string{"exec", "--user", "root", id}
	args = append(args, command...)
	if _, err := runDockerCommand(ctx, args...); err != nil {
		return fmt.Errorf("exec in container %q: %w", id, err)
	}
	return nil
}
